services:
  postgres-db:
    image: postgres:16
    container_name: taskmanager-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - taskmanager-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - taskmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  taskmanager-api:
    build: .
    container_name: taskmanager-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JWT__Secret=${JWT_SECRET}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
    ports:
      - "5001:8080"
    networks:
      - taskmanager-network
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  taskmanager-data:

networks:
  taskmanager-network:
    driver: bridge

